#config_version=6
#this mode is a branch of the "base" mode for a single player game

mode:
    start_events: 
      - carousel_single_player_selected
      - mode_single_player_start
      - ball_started{machine.selected_game_mode=='single_player'}
    priority: 801
event_player:
    mode_single_player_started:
      - enable_prevent_drain #this was not on - addded 3-26-2025
      - enable_p1_flipper
      - enable_single_player
      - enable_front_lock #this is so only the back lock ejects a ball for a single ball game
    mode_unlimited_multiball_started:  
      - enable_p1_flipper
      - enable_single_player
      - disable_front_lock
      - disable_back_lock
    p1_disap_t_roll_hit{device.counters.single_player_lives.value>=2}:
      - start_tunnel_multiball
      - eject_all #this is needed because for some reason after the first game - will not eject balls 
      - disable_front_lock
      - disable_back_lock
    p2_disap_t_roll_hit{device.counters.single_player_lives.value>=2}:
      - start_tunnel_multiball
      - eject_all #this is needed because for some reason after the first game - will not eject balls 
      - disable_front_lock
      - disable_back_lock   
    # end_tunnel_multiball: enable_front_lock #this is to make it one ball in play after tunnel multiball
    multiball_lock_etm_sp_full:
      - lives_counter_enable
multiball_locks:    
    etm_sp:
        balls_to_lock: 3
        enable_events: end_tunnel_multiball
        disable_events: round1end, start_tunnel_multiball  
        lock_devices: bd_trough_front, bd_trough_back
        balls_to_replace: 0 #A value of 0 means the lock will never replace balls to the playfield from the default source (bd_trough_front), and -1 means it will always replace balls
        locked_ball_counting_strategy: physical_only
counters:
    single_player_lives:
        count_events: s_p1_trough4_active, s_p2_trough4_active        
        events_when_complete: round1end
        starting_count: 5
        count_interval: 1
        direction: down
        count_complete_value: 0
        reset_on_complete: false
        control_events:
          - event: logicblock_single_p1_hunter_group_count_complete
            action: add
            value: 1           
          - event: logicblock_single_p2_hunter_group_count_complete
            action: add
            value: 1 
        disable_events: start_tunnel_multiball
        enable_events: mode_single_player_started, lives_counter_enable #{device.counters.single_player_lives.value > 0} # added lives_counter_enable and commented out 10-25-2025 #timer_p1_tunnel_multiball_complete{device.counters.single_player_lives.value > 0}, timer_p2_tunnel_multiball_complete{device.counters.single_player_lives.value > 0} #note 3-19-2025 not sure if the value greater than 0 works and why I would add that.
        debug: true 
    single_p1_hunter_group_count:
        count_events: p1_hunter_shot_group_complete
        events_when_hit: p1_hunter_group_done
        starting_count: 0
        direction: up
        persist_state: true 
        count_complete_value: 3
        reset_on_complete: true
        disable_on_complete: false
        disable_events: mode_double_player_started, mode_colab_started
        multiple_hit_window: 500ms               
    single_ p2_hunter_group_count:
        count_events: p2_hunter_shot_group_complete
        events_when_hit: p2_hunter_group_done
        starting_count: 0
        direction: up
        persist_state: true 
        count_complete_value: 3
        reset_on_complete: true
        disable_on_complete: false
        multiple_hit_window: 500ms
        disable_events: mode_double_player_started, mode_colab_started     
show_player:
    player_total_score:
        P1_score:
            show_tokens:
                txt: "{current_player.total_score:0>1,d}"
            key: p1score
        P2_score:
            show_tokens:
                txt: "{current_player.total_score:0>1,d}"
            key: p2score
    player_single_player_lives: #need to make sure this is the player variable
        P1_lives:
            show_tokens:
                txt: "{current_player.single_player_lives:0>1d}"
            key: p1lives1
        P2_lives:
            show_tokens:
                txt: "{current_player.single_player_lives:0>1d}"
            key: p1lives2
    player_timer_unlimited_multiball_variable:  #need to make sure this is the player variable
        P1_timer:
            show_tokens:
                txt: "{current_player.timer_unlimited_multiball_variable:0>1d}"
            key: timer1
        P2_timer:
            show_tokens:
                txt: "{current_player.timer_unlimited_multiball_variable:0>1d}"
            key: timer2
variable_player:
#Player 1 Side     
    logicblock_single_player_lives_updated:
        single_player_lives:
           int: value
           action: set
#to combine Player 2 side score into Player 1
    player_p1_score:
        total_score:
           int: current_player.p1_score + current_player.p2_score
           action: set
    player_p2_score:
        total_score:
           int: current_player.p1_score + current_player.p2_score
           action: set      
    player_p1_egg_bonus:
        total_egg_bonus:
           int: current_player.p1_egg_bonus + current_player.p2_egg_bonus
           action: set
    player_p2_egg_bonus:
        total_egg_bonus:
           int: current_player.p1_egg_bonus + current_player.p2_egg_bonus
           action: set


sound_player:
    mode_single_player_started: 
      player_start:
         action: play 

slide_player:
  mode_single_player_started:
    game_single:
      action: play
      priority: 20000
      target: display1
