#config_version=6

mode:
    start_events: ball_starting
    priority: 960
    events_when_started: enable_prevent_drain

event_player:

  timer_reset_hold_timer_complete: 
    - disableAutofire #disable the flippers and slingshot autofire
    - disable_p1_flipper
    - disable_single_player
    - disable_competitive
    - enable_front_lock
    - enable_back_lock
    - end_game
ball_saves:
    prevent_drain: #This is to have lives counter work and not have the ball drains count in the front trough
        enable_events: enable_prevent_drain
        disable_events: disable_prevent_drain
        auto_launch: false
        balls_to_save: -1 #unlimited
        debug: yes
multiball_locks:
    bd_trough_front:
        balls_to_lock: 2
        enable_events: enable_front_lock
        disable_events: disable_front_lock
        lock_devices: bd_trough_front
        balls_to_replace: 0 #A value of 0 means the lock will never replace balls to the playfield from the default source (bd_trough_front), and -1 means it will always replace balls
        locked_ball_counting_strategy: physical_only
    bd_trough_back:
        balls_to_lock: 2
        enable_events: enable_back_lock
        disable_events: disable_back_lock
        lock_devices: bd_trough_back
        balls_to_replace: 0 #A value of 0 means the lock will never replace balls to the playfield from the default source (bd_trough_front), and -1 means it will always replace balls
        locked_ball_counting_strategy: physical_only
timers:
  reset_hold_timer:
    start_value: 3
    end_value: 0
    direction: down
    tick_interval: 1s
    control_events:
      - action: start
        event: sw_end_game_active
      - action: reset
        event: sw_end_game_inactive
shots:
#Player 1 side
    p1_r_drain_shot:
        switch: s_p1_r_drain
#Player 2 side
    p2_r_drain_shot:
        switch: s_p2_r_drain

variable_player:
  timer_reset_hold_timer_tick:
    reset_progress_var:
      int: ticks
      action: set
  sw_end_game_inactive:
    reset_progress_var:
      int: 0
      action: set

show_player:
    mode_base_started:
        base_gi:
            speed: 1
    s_p1_launcher_active:
        release:
            loops: 8
            show_tokens:
                led: l_p2_release
                color: tt_green
    s_p2_launcher_active:
        release:
            loops: 8
            show_tokens:
                led: l_p1_release
                color: tt_green

slide_player:
  mode_base_started: base

sound_player:
  ball_started: GameStartExplosions
  s_p1_l_flipper_button_active: FlipperFlap
  s_p1_r_flipper_button_active: FlipperFlap
  s_p1_l_flipper_button_far_active: FlipperFlap
  s_p1_r_flipper_button_far_active: FlipperFlap
  s_p2_l_flipper_button_active: FlipperFlap
  s_p2_r_flipper_button_active: FlipperFlap
  ball_drain: BallDrainIntoTrough
