#config_version=6
#this mode is a branch of the "base" mode for a double player game

mode:
    start_events: 
      - carousel_double_player_selected
      - mode_double_player_start
      - ball_started{machine.selected_game_mode=='double_player'}
    priority: 802
event_player:
    mode_double_player_started:
      - enable_p1_flipper
      - enable_double_player
      - enable_prevent_drain       
    mode_unlimited_multiball_started: 
      - enable_p1_flipper
      - enable_double_player
    logicblock_lives_front_counter_complete{device.counters.lives_back_counter.value<=0}: round1end
    logicblock_lives_back_counter_complete{device.counters.lives_front_counter.value<=0}: round1end
    p1_disap_t_roll_hit{device.counters.lives_front_counter.value>=1}: 
      - start_tunnel_multiball
      - start_tunnel_multiball_accrual
      - eject_all #this is needed because for some reason after the first game - will not eject balls 
      - disable_front_lock
      - disable_back_lock
    p2_disap_t_roll_hit{device.counters.lives_back_counter.value>=1}: 
      - start_tunnel_multiball
      - start_tunnel_multiball_accrual
      - eject_all #this is needed because for some reason after the first game - will not eject balls 
      - disable_front_lock
      - disable_back_lock
      - reset_target_tunnel
    multiball_lock_etm_dp_full:
      - lives_counter_enable
multiball_locks:    
    etm_dp:
        balls_to_lock: 2
        enable_events: end_tunnel_multiball
        disable_events: round1end, start_tunnel_multiball  
        lock_devices: bd_trough_front, bd_trough_back
        balls_to_replace: 0 #A value of 0 means the lock will never replace balls to the playfield from the default source (bd_trough_front), and -1 means it will always replace balls
        locked_ball_counting_strategy: physical_only
counters:
    lives_front_counter:
        count_events: s_p1_trough4_active       
        starting_count: 3
        count_interval: 1
        direction: down
        count_complete_value: 0
        reset_on_complete: false
        control_events:
          - event: logicblock_p1_hunter_group_count_complete
            action: add
            value: 1            
        disable_events: p1_disap_t_roll_hit, mode_single_player_started 
        enable_events: mode_double_player_started, lives_counter_enable{device.counters.lives_front_counter.value>=1} # added 10-26-2025 and removed: timer_p1_tunnel_multiball_complete{device.counters.lives_front_counter.value > 0}
        debug: true 
    lives_back_counter:
        count_events: s_p2_trough4_active
        starting_count: 3
        count_interval: 1
        direction: down
        count_complete_value: 0          
        reset_on_complete: false
        control_events:
          - event: logicblock_p2_hunter_group_count_complete
            action: add
            value: 1    
        disable_events: p2_disap_t_roll_hit, mode_single_player_started 
        enable_events: mode_double_player_started, lives_counter_enable{device.counters.lives_back_counter.value>=1} # added 10-26-2025 and removed: timer_p2_tunnel_multiball_complete{device.counters.lives_back_counter.value > 0} 
    p1_hunter_group_count:
        count_events: p1_hunter_shot_group_complete
        events_when_hit: p1_hunter_group_done
        starting_count: 0
        direction: up
        persist_state: true 
        count_complete_value: 3
        reset_on_complete: true
        disable_on_complete: false
        disable_events: mode_single_player_started, mode_colab_started
        multiple_hit_window: 500ms               
    p2_hunter_group_count:
        count_events: p2_hunter_shot_group_complete
        events_when_hit: p2_hunter_group_done
        starting_count: 0
        direction: up
        persist_state: true 
        count_complete_value: 3
        reset_on_complete: true
        disable_on_complete: false
        multiple_hit_window: 500ms
        disable_events: mode_single_player_started, mode_colab_started        

show_player:
    player_p1_score:
        P1_score:
            show_tokens:
                txt: "{current_player.p1_score:0>1,d}"
            key: p1score
    player_p2_score:
        P2_score:
            show_tokens:
                txt: "{current_player.p2_score:0>1,d}"
            key: p2score
    player_lives_front_count: #need to make sure this is the player variable
        P1_lives:
            show_tokens:
                txt: "{current_player.lives_front_count:0>1d}"
            key: p1lives
    player_timer_unlimited_multiball_variable{value>0}:  #need to make sure this is the player variable
        P1_timer:
            show_tokens:
                txt: "{current_player.timer_unlimited_multiball_variable:0>1d}"
            key: timer1
        P2_timer:
            show_tokens:
                txt: "{current_player.timer_unlimited_multiball_variable:0>1d}"
            key: timer2
    player_lives_back_count:
        P2_lives:
            show_tokens:
                txt: "{current_player.lives_back_count:0>1d}"
            key: p2lives

variable_player:
 #Player 1 Side     
    logicblock_lives_front_counter_updated:
        lives_front_count:
           int: value
           action: set           
 #Player 2 Side     
    logicblock_lives_back_counter_updated:
        lives_back_count:
           int: value
           action: set        



sound_player:
    mode_double_player_started: 
      player_start:
         action: play   

slide_player:
  mode_double_player_started:
    game_base:
      action: play
      priority: 20000
      target: display1
